import numpy as np
import matplotlib.pyplot as plt

# ==============================================================================
# GTS v9.3 STATISTICAL VALIDATOR
# ------------------------------------------------------------------------------
# Framework: Geometric Unification Theory (GTS)
# Purpose: Direct comparison of Einsteinian GR vs. GTS against Observed Data.
#
# This script calculates the Residual Error and RMSE (Root Mean Square Error)
# to quantify the accuracy improvement provided by the GTS Omega Phase.
# ==============================================================================

# --- DATASET: OBSERVATIONAL VALIDATION ---
# Stellar objects ranging from standard stars to dense degenerate dwarfs.
names = ["Sun", "α Cen A", "Sirius B", "40 Eri B", "Stein 2051 B", "Procyon B"]

# General Relativity (GR) Predictions for Gravitational Redshift (rho)
# These represent the "Standard Model" baseline.
rho = np.array([2.12e-06, 1.91e-06, 2.67e-04, 8.69e-05, 1.30e-04, 1.06e-04])

# Real Observational Redshift (z_real)
# Values obtained from high-resolution spectroscopy (Gaia, Hubble, Ground-based).
z_real = np.array([2.12e-06, 1.80e-06, 2.88e-04, 7.10e-05, 1.30e-04, 9.70e-05])

# GTS Model v9.3 Predictions
# Predictions generated by the GTS Omega Engine (Topological Impedance model).
z_gts = np.array([2.12e-06, 1.92e-06, 2.78e-04, 8.74e-05, 1.32e-04, 1.07e-04])

# --- RESIDUAL CALCULATIONS ---
# A "Residual" is the distance between a model's prediction and reality.
# Residual = (Predicted Value - Observed Value).
# A perfect theory would result in a Residual of exactly 0.
res_gr = rho - z_real
res_gts = z_gts - z_real

# --- RMSE CALCULATION (THE STATISTICAL SCORE) ---
# Root Mean Square Error is the standard metric for model accuracy.
# It squares the errors (penalizing large misses) and takes the average.
rmse_gr = np.sqrt(np.mean(res_gr**2))
rmse_gts = np.sqrt(np.mean(res_gts**2))

# Calculate the Accuracy Improvement Percentage
# This shows how much more "reliable" GTS is compared to General Relativity.
improvement = (1 - (rmse_gts / rmse_gr)) * 100

# --- OUTPUT REPORT ---
print(f"{'GTS MODEL VALIDATION SUMMARY':^40}")
print("=" * 40)
print(f"RMSE General Relativity: {rmse_gr:.2e}")
print(f"RMSE GTS v9.3:           {rmse_gts:.2e}")
print("-" * 40)
print(f"GTS ACCURACY BOOST:      {improvement:.2f}%")
print("=" * 40)

# --- RESIDUAL DRIFT PLOT ---
# This plot visualizes the "drift" of theories away from the ground truth.
plt.figure(figsize=(12, 7), facecolor="#0d0d0d")
ax = plt.gca()
ax.set_facecolor("black")

# Plotting the zero-line (The "Perfect Theory" baseline representing Reality)
plt.axhline(0, color="white", linestyle="-", alpha=0.3, label="Reality (Perfect Fit)")

# General Relativity Residuals (Red)
# Shows where Einstein's math overshoots or undershoots reality.
plt.plot(rho, res_gr, "ro--", label=f"GR Residuals (RMSE: {rmse_gr:.1e})", alpha=0.6)

# GTS Model Residuals (Cyan)
# Shows the improved fit provided by the Topological Phase Transition.
plt.plot(rho, res_gts, "c-o", label=f"GTS v9.3 Residuals (RMSE: {rmse_gts:.1e})", lw=2)

# Styling and Labels
plt.xscale("log")  # Using log scale to handle the wide range of causal densities
plt.xlabel("Causal Density (rho)", color="white")
plt.ylabel("Residual Error (Model - Reality)", color="white")
plt.title(
    f"GTS v16.1: Statistical Accuracy Improvement ({improvement:.1f}%)", color="cyan"
)
plt.legend(facecolor="#1a1a1a", labelcolor="white")
plt.grid(True, which="both", ls="-", color="#333333", alpha=0.4)
plt.tick_params(colors="white")

# Save the proof for your GitHub repository
plt.savefig("gts_statistical_validation.png")
print(
    "\n[SUCCESS] Statistical report generated and saved as 'gts_statistical_validation.png'"
)
